---
title: "DATA607_w9 - Web APIs"
author: "David Simbandumwe"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document:
    latex_engine: xelatex
    extra_dependencies:
    - geometry
    - multicol
    - multirow
  rmdformats::robobook:
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(tidyverse)
library(jsonlite)
library(httr)

```


# Introduction
The New York Times web site provides a rich set of APIs, as described here: https://developer.nytimes.com/apis. For this assignment I selected the top stories api. 

1. created an account
2. configured the authentication
3. Called teh API: https://api.nytimes.com/svc/topstories/v2/science.json
4. Created a data frame: science_df




```{r}


json_url <- "https://api.nytimes.com/svc/topstories/v2/science.json?api-key=ueC6BKg7iaXGRbGD8DALuBFoANFPfalV"
science_df = fromJSON(json_url,
                   simplifyDataFrame = TRUE,
                   flatten = TRUE
            )$results %>%
            as_tibble() %>%
            flatten()
    

?fromJSON

```




# Conclusions
The flattened record contains 24 obserservations with 19 variables.





