---
title: "DATA 607 Final Project: Predicting Financial Well Being"
author: "David Simbandumwe"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(utils)

library(tidyverse)
library(tidymodels)
library(textrecipes)
library(discrim)
library(dplyr)
library(plyr)

library(stringr)
library(glue)
library(purrr)

library(visdat)
#library(gt)
library(GGally)
#library(ggmap)
library(vip)



```


# Overview






## Setup

```{r, results="hide"}
set.seed(1234)
rm(list=ls())
```


```{r, include=FALSE, error=TRUE}

fun_file_name <- glue(getwd(), "/ProjectFinal/DATA607_Functions.R")
source(fun_file_name)

```



## Functions




# Data Collection



## Download and Tidy dataset from CFPB

```{r}

cfpb_df <- getCFPBFile()

cfpb_df$cfpb_score_4cat <- cut(cfpb_df$cfpb_score, breaks = c(-10, 40, 60, 80, 100),
                           labels = c("< 40","40-60","60-80","80-100"),
                           right = FALSE,
                           include.lowest=TRUE)  

#cfpb_df <- cfpb_df %>% select(-c(sample_pop,poverty_stat,cfpb_score,fs_lm_score,fs_kh_score,fs_skills_score))
#cfpb_df <- cfpb_df %>% select(cfpb_score_4cat, econ_hh_income, econ_save_rate, house_value, house_mortgage, age_8cat, race)
#cfpb_df <- cfpb_df %>% select(cfpb_score_4cat,fs_lm_score,fs_kh_score,age_8cat,age_generation,econ_hh_income,hh_size,race)
cfpb_df <- cfpb_df %>% select(cfpb_score_4cat, econ_hh_income, econ_save_rate, house_value, house_mortgage, age_8cat, race)


#cfpb_df %>% dplyr::count(cfpb_score_4cat)
cfpb_df <- slice_sample(cfpb_df,n=2000) 


```



## Machine Learning


### split data

```{r}


# Put 3/4 of the data into the training set 
cfpb_split <- initial_split(cfpb_df, prop = 0.8, strata = cfpb_score_4cat)

# Create dataframes for the two sets:
cfpb_train_data <- training(cfpb_split) 
cfpb_test_data <- testing(cfpb_split)


```



### define recipts 

```{r}

cfpb_rec <-
  recipe(cfpb_score_4cat ~ ., data = cfpb_train_data) %>%
  step_naomit(everything(), skip = TRUE) %>% 
  step_novel(all_nominal(), -all_outcomes()) %>%
  step_normalize(all_numeric(), -all_outcomes()) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_zv(all_numeric(), -all_outcomes()) %>%
  step_corr(all_predictors(), threshold = 0.7, method = "spearman") 


summary(cfpb_rec)

```



### prep data

```{r}


cfpb_prepped_data <- 
  cfpb_rec %>% 
  prep() %>% 
  juice() 

glimpse(cfpb_prepped_data)



```



### folds and spec

```{r}

cv_folds <-
 vfold_cv(cfpb_train_data, 
          v = 5, 
          strata = cfpb_score_4cat) 


rf_spec <- 
  rand_forest() %>% 
  set_engine("ranger", importance = "impurity") %>% 
  set_mode("classification")


```



### tune workflow

```{r}


# workflow
rf_wflow <-
 workflow() %>%
 add_recipe(cfpb_rec) %>% 
 add_model(rf_spec) 


# resample
rf_res <-
  rf_wflow %>% 
  fit_resamples(
    resamples = cv_folds, 
    metrics = metric_set(recall, precision, f_meas,accuracy, kap,roc_auc, sens, spec),
    control = control_resamples(save_pred = TRUE)
    ) 
rf_res %>%  collect_metrics(summarize = TRUE)


rf_metrics <- 
  rf_res %>% 
  collect_metrics(summarise = TRUE) %>%
  mutate(model = "Random Forest")


```



### Final Fit

```{r}


last_fit_rf <- last_fit(rf_wflow, 
                        split = cfpb_split,
                        metrics = metric_set(recall, precision, f_meas,accuracy, kap, roc_auc, sens, spec)
                        )


last_fit_rf %>% 
  collect_metrics()


last_fit_rf %>% 
  pluck(".workflow", 1) %>%   
  extract_fit_parsnip() %>% 
  vip(num_features = 25)


last_fit_rf %>%
  collect_predictions() %>% 
  conf_mat(cfpb_score_4cat, .pred_class) %>% 
  autoplot(type = "heatmap")


# last_fit_rf %>%
#   collect_predictions() %>%
#   roc_curve(cfpb_score_4cat, .pred_above) %>%
#   autoplot()
# 



```



## Download and Tidy dataset from FED

```{r}

fed_df <- getFedFile()
fed_df <- fed_df %>% drop_na()
fed_df <- fed_df %>% filter(!(econ_saving == "" |  credit_guess =="" | health ==""))
fed_df <- slice_sample(fed_df,n=4000) 
fed_df$credit_guess <- str_replace_all(fed_df$credit_guess, "[^[:alnum:]]", "")

fed_df$cfpb_score <- as.numeric(as.character(fed_df$cfpb_score)) 

fed_df$cfpb_score_4cat <- cut(fed_df$cfpb_score, breaks = c(-10, 40, 60, 80, 100),
                           labels = c("< 20","40-60","60-80","80-100"),
                           right = FALSE,
                           include.lowest=TRUE)  

fed_df %>% dplyr::count(cfpb_score_4cat)

# fed_df <- fed_df %>% select(gender,age_4cat,household_size, race, cfpb_score_4cat,
#                             marital_status, house_ownership, edu_cat, econ_hh_income
#                             )


#fed_df <- fed_df %>% select(cfpb_score_4cat, econ_fin_ok, econ_skip_med, econ_pay_exp400, age_7cat, econ_saving, credit_guess )
fed_df <- fed_df %>% select(cfpb_score_4cat, econ_fin_ok, econ_skip_med, econ_pay_exp400, age_7cat, econ_saving, credit_guess, health, econ_inc_4cat )




```



### split data

```{r}


# Put 3/4 of the data into the training set 
fed_split <- initial_split(fed_df, 
                           prop = .8, 
                           strata = cfpb_score_4cat)

# Create dataframes for the two sets:
fed_train_data <- training(fed_split) 
fed_test_data <- testing(fed_split)


```



### define recipts 

```{r}

fed_rec <-
  recipe(cfpb_score_4cat ~ ., data = fed_train_data) %>%
  step_naomit(everything(), skip = TRUE) %>% 
  step_novel(all_nominal(), -all_outcomes()) %>%
  step_normalize(all_numeric(), -all_outcomes()) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_zv(all_numeric(), -all_outcomes()) %>%
  step_corr(all_predictors(), threshold = 0.7, method = "spearman", skip = TRUE) 


summary(fed_rec)

```



### folds and spec

```{r}

cv_fed_folds <-
 vfold_cv(fed_train_data, 
          v = 5, 
          strata = cfpb_score_4cat) 


rf_fed_spec <- 
  rand_forest() %>% 
  set_engine("ranger", importance = "impurity") %>% 
  set_mode("classification")


```


### tune workflow

```{r}


# workflow
rf_fed_wflow <-
 workflow() %>%
 add_recipe(fed_rec) %>% 
 add_model(rf_fed_spec) 


# resample
rf_fed_res <-
  rf_fed_wflow %>% 
  fit_resamples(
    resamples = cv_fed_folds, 
    metrics = metric_set(recall, precision, f_meas,accuracy, kap,roc_auc, sens, spec),
    control = control_resamples(save_pred = TRUE)
    ) 

rf_fed_res %>%  collect_metrics(summarize = TRUE)


rf_fed_metrics <- 
  rf_fed_res %>% 
  collect_metrics(summarise = TRUE) %>%
  mutate(model = "Random Forest")


```



### Final Fit

```{r}


last_fit_fed_rf <- last_fit(rf_fed_wflow, 
                        split = fed_split,
                        metrics = metric_set(recall, precision, f_meas,accuracy, kap, roc_auc, sens, spec)
                        )


last_fit_fed_rf %>% 
  collect_metrics()


last_fit_fed_rf %>% 
  pluck(".workflow", 1) %>%   
  extract_fit_parsnip() %>% 
  vip(num_features = 10)


last_fit_fed_rf %>%
  collect_predictions() %>% 
  conf_mat(cfpb_score_4cat, .pred_class) %>% 
  autoplot(type = "heatmap")


# last_fit_fed_rf %>% 
#   collect_predictions() %>% 
#   roc_curve(cfpb_score_4cat, .pred_above) %>% 
#   autoplot()



```



# Analysis


# Conclusion
	
	
	
	
	
	
	
