---
title: "DATA 607 Final Project: Visualization"
author: "David Simbandumwe"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)

library(utils)

library(tidyverse)
library(tidymodels)
library(textrecipes)
library(discrim)
library(dplyr)
library(plyr)
library(naivebayes)

library(glue)
library(vip)

library(GGally)
library(gridExtra)

```


# Overview
Visualize the results of the CFPB and the FED surveys

## Setup

```{r}

set.seed(1234)
rm(list=ls())

```



```{r, include=FALSE, error=TRUE}

fun_file_name <- glue(getwd(), "/ProjectFinal/DATA607_Functions.R")
source(fun_file_name, local = knitr::knit_global())

```



## Download and Tidy dataset from CFPB

```{r}

# get cfpb file
cfpb_df <- getCFPBFile()
cfpb_df$cfpb_score_4cat <- cut(cfpb_df$cfpb_score, breaks = c(-10, 40, 60, 80, 100),
                           labels = c("< 40","40-60","60-80","80-100"),
                           right = FALSE,
                           include.lowest=TRUE) 
cfpb_df <- cfpb_df %>% filter(cfpb_score >= 0)

# reduce cfpb data set
cfpb_df <- slice_sample(cfpb_df, weight_by=cfpb_score_4cat ,n=4000) 
cfpb_df <- cfpb_df %>% select(cfpb_score, econ_save_rate, house_mortgage, age_8cat, econ_hh_income)


summary(cfpb_df)

```



## Visualize CFPB survey data

```{r}

# looks like the correlation breaks down by education level
ggscatmat(data=cfpb_df, corMethod = "spearman", alpha=0.2)
ggscatmat(data=cfpb_df, color="edu_level", corMethod = "spearman", alpha=0.2)
ggscatmat(data=cfpb_df, color="econ_hh_income", corMethod = "spearman", alpha=0.2)


```






```{r}

# econ_hh_income 
ggplot(cfpb_df, aes(x=econ_hh_income)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "econ_hh_income")

ggplot(data = cfpb_df) +
  geom_boxplot(mapping = aes(x=cfpb_score, y=econ_hh_income, color=econ_hh_income)) +
  labs (title = "econ_hh_income")

ggplot(cfpb_df,
    aes(cfpb_score, fill = econ_hh_income, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by econ_hh_income)")



# econ_save_rate
ggplot(cfpb_df, aes(x=econ_save_rate)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "econ_save_rate")

ggplot(data = cfpb_df) +
  geom_boxplot(mapping = aes(x=cfpb_score, y=econ_save_rate, color=econ_save_rate)) +
  labs (title = "econ_save_rate")

ggplot(cfpb_df,
    aes(cfpb_score, fill = econ_save_rate, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by econ_save_rate)")



# age_8cat
ggplot(cfpb_df, aes(x=age_8cat)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "age_8cat")

ggplot(data = cfpb_df) +
  geom_boxplot(mapping = aes(x=cfpb_score, y=age_8cat, color=age_8cat)) +
  labs (title = "age_8cat")

ggplot(cfpb_df,
    aes(cfpb_score, fill = age_8cat, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by age_8cat)")



# house_mortgage
ggplot(cfpb_df, aes(x=house_mortgage)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "house_mortgage")

ggplot(data = cfpb_df) +
  geom_boxplot(mapping = aes(x=cfpb_score, y=house_mortgage, color=house_mortgage)) +
  labs (title = "house_mortgage")

ggplot(cfpb_df,
    aes(cfpb_score, fill = house_mortgage, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by house_mortgage)")



# race
ggplot(cfpb_df, aes(x=race)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "race")

ggplot(data = cfpb_df) +
  geom_boxplot(mapping = aes(x=cfpb_score, y=race, color=race)) +
  labs (title = "race")

ggplot(cfpb_df,
    aes(cfpb_score, fill = race, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by race)")


```




# Federal Reserve


## Download and Tidy dataset from FEd

```{r}

# get fed file
fed_df <- getFedFile()
fed_df$cfpb_score_4cat <- cut(fed_df$cfpb_score, breaks = c(-10, 40, 60, 80, 100),
                           labels = c("< 40","40-60","60-80","80-100"),
                           right = FALSE,
                           include.lowest=TRUE) 

# reduce cfpb dataset
fed_df <- slice_sample(fed_df, weight_by=cfpb_score_4cat ,n=4000) 

fed_df <- fed_df %>% select(cfpb_score, age_7cat, econ_saving, econ_inc_4cat, econ_fin_ok, 
                            econ_pay_exp400, econ_skip_med)

summary(fed_df)

```



## Visualize Fed survey data

```{r}

# looks like the correlation breaks down by education level
ggscatmat(data=fed_df, corMethod = "spearman", alpha=0.2)
ggscatmat(data=fed_df, color="econ_fin_ok", corMethod = "spearman", alpha=0.2)
ggscatmat(data=fed_df, color="econ_skip_med", corMethod = "spearman", alpha=0.2)


```




```{r}


# age_7cat
ggplot(fed_df, aes(x=age_7cat)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "age_7cat")

ggplot(data = fed_df) +
  geom_boxplot(mapping = aes(x=cfpb_score, y=age_7cat, color=age_7cat)) +
  labs (title = "age_7cat")

ggplot(fed_df,
    aes(cfpb_score, fill = age_7cat, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by age_7cat)")



# econ_saving
ggplot(fed_df, aes(x=econ_saving)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "econ_saving")

ggplot(data = fed_df) +
  geom_boxplot(mapping = aes(x=cfpb_score, y=econ_saving, color=econ_saving)) +
  labs (title = "econ_saving")

ggplot(fed_df,
    aes(cfpb_score, fill = econ_saving, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by econ_saving)")



# econ_inc_4cat
ggplot(fed_df, aes(x=econ_inc_4cat)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "econ_inc_4cat")

ggplot(data = fed_df) +
  geom_boxplot(mapping = aes(x=cfpb_score, y=econ_inc_4cat, color=econ_inc_4cat)) +
  labs (title = "econ_inc_4cat")

ggplot(fed_df,
    aes(cfpb_score, fill = econ_inc_4cat, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by econ_inc_4cat)")



# econ_fin_ok
ggplot(fed_df, aes(x=econ_fin_ok)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "econ_fin_ok")

ggplot(data = fed_df) +
  geom_boxplot(mapping = aes(x=cfpb_score, y=econ_fin_ok, color=econ_fin_ok)) +
  labs (title = "econ_fin_ok")

ggplot(fed_df,
    aes(cfpb_score, fill = econ_fin_ok, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by econ_fin_ok)")



# econ_skip_med
ggplot(fed_df, aes(x=econ_skip_med)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "econ_skip_med")

ggplot(data = fed_df) +
  geom_boxplot(mapping = aes(x=cfpb_score, y=econ_skip_med, color=econ_skip_med)) +
  labs (title = "econ_skip_med")

ggplot(fed_df,
    aes(cfpb_score, fill = econ_skip_med, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by econ_skip_med)")




# econ_pay_exp400
ggplot(fed_df, aes(x=econ_pay_exp400)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "econ_pay_exp400")

ggplot(data = fed_df) +
  geom_boxplot(mapping = aes(x=cfpb_score, y=econ_pay_exp400, color=econ_pay_exp400)) +
  labs (title = "econ_skip_med")

ggplot(fed_df,
    aes(cfpb_score, fill = econ_pay_exp400, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by econ_pay_exp400)")




```













	
