---
title: "DATA 607 Final Project: Predicting Financial Well Being"
author: "David Simbandumwe"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)

library(utils)

library(tidyverse)
library(tidymodels)
library(textrecipes)
library(discrim)
library(dplyr)
library(plyr)
library(naivebayes)

library(glue)
library(vip)

library(GGally)

```


# Overview



## Setup

```{r}

set.seed(1234)
rm(list=ls())

```



```{r, include=FALSE, error=TRUE}

fun_file_name <- glue(getwd(), "/ProjectFinal/DATA607_Functions.R")
source(fun_file_name, local = knitr::knit_global())

```



## Download and Tidy dataset from CFPB

```{r}

cfpb_df <- getCFPBFile()

cfpb_df <- slice_sample(cfpb_df,n=5000) 
#cfpb_df <- cfpb_df %>% select(-c(sample_pop,poverty_stat,fs_skills_score,fs_lm_score, fs_kh_score))




```





```{r}

# looks like the correlation breaks down by education level
ggscatmat(data=cfpb_df, corMethod = "spearman", alpha=0.2)
ggscatmat(data=cfpb_df, color="edu_level", corMethod = "spearman", alpha=0.2)
ggscatmat(data=cfpb_df, color="econ_hh_income", corMethod = "spearman", alpha=0.2)


```






```{r}

par(mfrow=c(2,2)) 


# age_8cat
ggplot(cfpb_df, aes(x=age_8cat)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "age_8cat")


ggplot(cfpb_df,
    aes(cfpb_score, fill = age_8cat, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by age_8cat)")

# age_generation
ggplot(cfpb_df, aes(x=age_generation)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "age_generation")


ggplot(cfpb_df,
    aes(cfpb_score, fill = age_generation, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by age_generation)")


# edu_level 
ggplot(cfpb_df, aes(x=edu_level)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "edu_level")


ggplot(cfpb_df,
    aes(cfpb_score, fill = edu_level, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by edu_level)")

# race
ggplot(cfpb_df, aes(x=race)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "race")


ggplot(cfpb_df,
    aes(cfpb_score, fill = race, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by race)")

# gender   
ggplot(cfpb_df, aes(x=gender)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "gender")


ggplot(cfpb_df,
    aes(cfpb_score, fill = gender, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, bins = 100, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by gender)")


# marital_status 
ggplot(cfpb_df, aes(x=marital_status)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "marital_status")


ggplot(cfpb_df,
    aes(cfpb_score, fill = marital_status, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by marital_status)")


```


```{r}

par(mfrow=c(2,2)) 

# hh_arrange
ggplot(cfpb_df, aes(x=hh_arrange)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "hh_arrange")


ggplot(cfpb_df,
    aes(cfpb_score, fill = hh_arrange, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by hh_arrange)")


# hh_size   
ggplot(cfpb_df, aes(x=hh_size)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "hh_size")


ggplot(cfpb_df,
    aes(cfpb_score, fill = hh_size, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by hh_size)")



# hh_earners
ggplot(cfpb_df, aes(x=hh_earners)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "hh_earners")


ggplot(cfpb_df,
    aes(cfpb_score, fill = hh_earners, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.2) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by hh_earners)")






 









```


```{r}


par(mfrow=c(2,2)) 

# econ_save_rate
ggplot(cfpb_df, aes(x=hh_arrange)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "hh_arrange")


ggplot(cfpb_df,
    aes(cfpb_score, fill = hh_arrange, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by hh_arrange)")


# house_ownership
ggplot(cfpb_df, aes(x=house_ownership)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "house_ownership")


ggplot(cfpb_df,
    aes(cfpb_score, fill = house_ownership, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by house_ownership)")


# house_value
ggplot(cfpb_df, aes(x=house_value)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "house_value")


ggplot(cfpb_df,
    aes(cfpb_score, fill = house_value, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by house_value)")


# house_mortgage
ggplot(cfpb_df, aes(x=house_mortgage)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "house_mortgage")


ggplot(cfpb_df,
    aes(cfpb_score, fill = house_mortgage, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by house_mortgage)")


# econ_hh_income 
ggplot(cfpb_df, aes(x=econ_hh_income)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "econ_hh_income")


ggplot(cfpb_df,
    aes(cfpb_score, fill = econ_hh_income, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by econ_hh_income)")




```



```{r}

# age_8cat
ggplot(cfpb_df, aes(x=age_8cat)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "age_8cat")


ggplot(cfpb_df,
    aes(cfpb_score, fill = age_8cat, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by age_8cat)")


# age_generation
ggplot(cfpb_df, aes(x=age_generation)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "age_generation")


ggplot(cfpb_df,
    aes(cfpb_score, fill = age_generation, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by age_generation)")


# edu_level 
ggplot(cfpb_df, aes(x=edu_level)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "edu_level")


ggplot(cfpb_df,
    aes(cfpb_score, fill = edu_level, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by edu_level)")

# race 
ggplot(cfpb_df, aes(x=race)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "race")


ggplot(cfpb_df,
    aes(cfpb_score, fill = race, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by race)")

# gender 
ggplot(cfpb_df, aes(x=gender)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "gender")


ggplot(cfpb_df,
    aes(cfpb_score, fill = gender, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by gender)")

# marital_status  
ggplot(cfpb_df, aes(x=marital_status)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "marital_status")


ggplot(cfpb_df,
    aes(cfpb_score, fill = marital_status, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by marital_status)")



```


```{r}

# metro     
ggplot(cfpb_df, aes(x=metro)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "metro")


ggplot(cfpb_df,
    aes(cfpb_score, fill = metro, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by metro)")

# region_4base  
ggplot(cfpb_df, aes(x=region_4base)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "region_4base")


ggplot(cfpb_df,
    aes(cfpb_score, fill = region_4base, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by region_4base)")

# region_9base  
ggplot(cfpb_df, aes(x=region_9base)) +
  geom_bar(color="white", fill="black", alpha = 0.6, size = 0.1) +
  coord_flip() +
  labs(title = "region_9base")


ggplot(cfpb_df,
    aes(cfpb_score, fill = region_9base, y = stat(density))) +
    geom_histogram(binwidth = 1, alpha = 0.7, color="white",size = 0.1) +
    geom_vline(aes(xintercept = mean(cfpb_score)), linetype = "dashed", size = 0.5) +
    scale_fill_brewer(palette="Spectral") +
    labs(title = "CFPB Score (by region_9base)")


```



# Federal Reserve


## Download and Tidy dataset from FEd

```{r}

# fed_df <- getFedFile()
# 
# fed_df <- slice_sample(fed_df,n=5000) 
# fed_df <- fed_df %>% select(-c(age_4cat, age_7cat, starts_with("age_"),starts_with("hh_child_")
#                                ,race_census
#                                ))
# 
# 
# count(fed_df$race_census)

```




# Analysis


# Conclusion
	
	
	
	
	
	
	
